

#Connection pool
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 50MB


  datasource:
    url: jdbc:mariadb://localhost:3306/apimp2db
    driver-class-name: org.mariadb.jdbc.Driver
    username: apimp2dbuser
    password: apimp2dbuser
    hikari:
      maximum-pool-size: 5   # ?? ??? ??
      minimum-idle: 2         # ?? ?? ??? ??
      idle-timeout: 30000     # ???? ?? ??? ???? ?? ?? (???)
      max-lifetime: 1800000   # ???? ?? ???? (???)
      connection-timeout: 2000 # ??? ?? ? ?? ?? ?? (???)

  #JPA Config
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never



#?? ??
logging:
  level:
    org.sommer: INFO
    org.springframework.security: TRACE

org:
  sommer:
    upload: upload